### ISSUE TITLE
bug: [postcss] (0 , _parse.default) is not a function 

### ISSUE THREAD

**Issue by muratkarabag** [saadeghi/daisyui#2524]
### What version of daisyUI are you using?

v4.0.5

### Which browsers are you seeing the problem on?

Other

### Reproduction URL

nothing

### Describe your issue

First of all thank you for this plugin. when I try to upgrade new version of daisy ui 4.0.5 I get error. I tried to update all npm packages but nothing is changed.
this is what I get error in terminal.
<img width="612" alt="Screenshot 2023-11-14 at 20 28 36" src="https://github.com/saadeghi/daisyui/assets/146127177/57718733-17d4-4fd5-9561-a3b4d2910eb1">

and these are what I use packages in my project.
<img width="272" alt="Screenshot 2023-11-14 at 20 30 44" src="https://github.com/saadeghi/daisyui/assets/146127177/0f63c3f0-b539-495c-81bb-292cdd34a97c">

**Comment by saadeghi** [comment]
Thanks for letting us know about the issue!  
Can you share a simple reproduction repo of the problem? It'll help us fix things faster. Without a reproduction repo, it's not easy to guess the problem.  
Thanks for helping make daisyUI better!

**Comment by muratkarabag** [comment]
Hi, this is reproduction repo I just install my packages and show up the error. This setup works with daisyui 3.9.4 version but it's not working on 4^ versions. I hope you can see the repo. Thank you again.
https://stackblitz.com/edit/nuxt-starter-nngef8?

**Comment by saadeghi** [comment]
It works if you separate the tailwind config file:  
https://stackblitz.com/edit/nuxt-starter-7nfzf8?file=tailwind.config.js

I don't know what's happening under the hood but for some reason the config inside `nuxt.config.ts` is not working as expected.  
Having a dedicated `tailwind.config.js` file is also the recommended way from Nuxt website: https://tailwindcss.nuxtjs.org/examples/daisyui


Let me know if you have a question.

**Comment by muratkarabag** [comment]
I'm sorry but i already separate config files in my own project. It didnt work with v4. I updated my example stackblitz. I use same code same configuration for daisyui 3.9.4 its work but v4 didnt.

**Comment by saadeghi** [comment]
Does the separated `tailwind.config.js` work for you?  
https://stackblitz.com/edit/nuxt-starter-7nfzf8?file=tailwind.config.js
